pref("extensions.nachoSD.firstRun", true);
pref("extensions.nachoSD.tab", 0);
pref("extensions.nachoSD.serverlistindex", -1);
pref("extensions.nachoSD.serverName", "pro");
pref("extensions.nachoSD.serverIP", "10.234.8.180");
pref("extensions.nachoSD.serverPort", "8080");
pref("extensions.nachoSD.user",'');
pref("extensions.nachoSD.autologin", false);
pref("extensions.nachoSD.OSnotif", true);
pref("extensions.nachoSD.popupnotif", true);
pref("extensions.nachoSD.factory", 'cr');
pref("extensions.nachoSD.query.atr1", '');
pref("extensions.nachoSD.query.val1", '');
pref("extensions.nachoSD.query.rel1", 'QBE.EQ.');
pref("extensions.nachoSD.query.act1", true);
pref("extensions.nachoSD.fff", '');
